---
abstract: 'Perl extension for comparing XML documents.'
author:
  - 'Kip Hampton <khampton@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-SemanticDiff
provides:
  XML::SemanticDiff:
    file: lib/XML/SemanticDiff.pm
    version: 1.0004
  XML::SemanticDiff::BasicHandler:
    file: lib/XML/SemanticDiff/BasicHandler.pm
    version: 1.0004
  XML::SemanticDiff::PathFinder:
    file: lib/XML/SemanticDiff.pm
  XML::SemanticDiff::PathFinder::Obj:
    file: lib/XML/SemanticDiff.pm
requires:
  Digest::MD5: 0
  Encode: 0
  XML::Parser: 0
  perl: 5.006
resources:
  repository: https://bitbucket.org/shlomif/perl-xml-semanticdiff
version: 1.0004
