---
name: XML-SemanticDiff
version: 0.97
author:
  - 'Kip Hampton <khampton@cpan.org>'
abstract: Perl extension for comparing XML documents.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::MD5: 0
  Encode: 0
  XML::Parser: 0
provides:
  XML::SemanticDiff:
    file: lib/XML/SemanticDiff.pm
    version: 0.97
  XML::SemanticDiff::BasicHandler:
    file: lib/XML/SemanticDiff/BasicHandler.pm
    version: 0.93
  XML::SemanticDiff::PathFinder:
    file: lib/XML/SemanticDiff.pm
  XML::SemanticDiff::PathFinder::Obj:
    file: lib/XML/SemanticDiff.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
