---
name: XML-SemanticDiff
version: 1.0000
author:
  - 'Kip Hampton <khampton@cpan.org>'
abstract: Perl extension for comparing XML documents.
license: perl
resources:
  Repository: http://svn.berlios.de/svnroot/repos/web-cpan/XML-SemanticDiff/
requires:
  Digest::MD5: 0
  Encode: 0
  XML::Parser: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.34
provides:
  XML::SemanticDiff:
    file: lib/XML/SemanticDiff.pm
    version: 1.0000
  XML::SemanticDiff::BasicHandler:
    file: lib/XML/SemanticDiff/BasicHandler.pm
    version: 0.94
  XML::SemanticDiff::PathFinder:
    file: lib/XML/SemanticDiff.pm
  XML::SemanticDiff::PathFinder::Obj:
    file: lib/XML/SemanticDiff.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
